
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/2

###
GET http://localhost:3000/categories/7

###
GET http://localhost:3000/categories/73

###
GET http://localhost:3000/categories/hello

### Dodawanie nowej kategorii | 8.8.3 inny token użyty do autoryzacji
POST http://localhost:3000/categories
Authorization: Bearer qEs8XSqkYrrw_fEq
Content-Type: application/json

{
   "name": "Art"
}

### Testowanie poprawności body
POST http://localhost:3000/categories
Content-Type: application/json

{ "name": "" }

### Testowanie poprawności body #2 - hack my id!
POST http://localhost:3000/categories
Content-Type: application/json

{
  "id": 2,
  "name": "Troll!"
}

### Testowanie poprawności body #3 - hack my fields...
POST http://localhost:3000/categories
Content-Type: application/json

{
  "id": 2,
  "name": "Troll!",
  "trollType": "Mountain"
}

### 3.7 Usuwanie kategorii | 8.8.2 dodanie uwierzytelnienia kluczem api
DELETE http://localhost:3000/categories/5
Authorization: Bearer cbbU7yWFGznUx6V4gxq1a
