### [C]reate new product:
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer cbbU7yWFGznUx6V4gxq1a

{
  "name": "Kubek",
  "price": 18.25,
  "description": "Napij się prosto z Cuba",
  "image": "https://picsum.photos/id/30/1280/901",
  "categoryId": 5
}

### [R]ead product (with some fake cookies):
GET http://localhost:3000/products/90
Set-Cookie: sessionId=38afes7a8; orderId=12;

### [R]ead products:
GET http://localhost:3000/products
Accept-Language: pl

### [R]ead products (Expect ERROR):
GET http://localhost:3000/products/test-file

### [R]ead products (Expect sample error):
GET http://localhost:3000/products/sample-error

### [R]ead products (Expect sample error in polish):
GET http://localhost:3000/products/sample-error
Accept-Language: pl

### [R]ead products (lang with q):
GET http://localhost:3000/products/sample-error
Accept-Language: fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, pl;q=0.5

### Search products by name:
GET http://localhost:3000/products?name=atu

### [R]ead product:
GET http://localhost:3000/products/2

### [U]pdate product
PATCH http://localhost:3000/products/2
Content-Type: application/json

{
  "description": "100% Porcelana"
}

### [D]elete product
DELETE http://localhost:3000/products/1
