### [C]reate new product:
POST http://localhost:3000/products
Content-Type: application/json

{

  "price": 18.25,
  "description": "Napij się prosto z Cuba",
  "image": "https://picsum.photos/id/30/1280/901",
  "categoryId": 5
}

### [R]ead product (with some fake cookies):
GET http://localhost:3000/products/90
Set-Cookie: sessionId=38afes7a8; orderId=12;

### [R]ead products:
GET http://localhost:3000/products

### [R]ead products (Expect ERROR):
GET http://localhost:3000/products/test-file

### [R]ead products (Expect Uknown error):
GET http://localhost:3000/products/sample-error

### Search products by name:
GET http://localhost:3000/products?name=atu

### [R]ead product:
GET http://localhost:3000/products/2

### [U]pdate product
PATCH http://localhost:3000/products/2
Content-Type: application/json

{
  "description": "100% Porcelana"
}

### [D]elete product
DELETE http://localhost:3000/products/1
